<?php
namespace App\Filament\Resources\BankChecks\Schemas;
use App\Models\BankCheck; use Filament\Forms\Components\DatePicker; use Filament\Forms\Components\Select; use Filament\Forms\Components\TextInput; use Filament\Forms\Components\Textarea; use Filament\Schemas\Components\Grid; use Filament\Schemas\Schema; use Illuminate\Database\Eloquent\Builder;
class BankCheckForm { public static function configure(Schema $s):Schema{return $s->components([Grid::make(2)->schema([
 Select::make('type')->label('نوع الشيك')->options(BankCheck::typeOptions())->required()->live()->default(BankCheck::TYPE_INCOMING), TextInput::make('document_number')->label('رقم المستند')->readOnly()->dehydrated(false)->placeholder('يولد تلقائيًا'),
 TextInput::make('check_number')->label('رقم الشيك')->required()->maxLength(100), TextInput::make('amount')->label('قيمة الشيك')->numeric()->minValue(.01)->step(.01)->required(),
 DatePicker::make('issue_date')->label('تاريخ الإصدار')->default(now())->native(false)->required(), DatePicker::make('due_date')->label('تاريخ الاستحقاق')->default(now())->native(false)->required(),
 Select::make('status')->label('حالة الشيك')->options(fn($get)=>BankCheck::statusOptions($get('type')))->required()->live()->default(fn($get)=>$get('type')===BankCheck::TYPE_OUTGOING?BankCheck::STATUS_PENDING_DELIVERY:BankCheck::STATUS_IN_HAND),
 DatePicker::make('cleared_date')->label('تاريخ التحصيل / الصرف')->native(false)->visible(fn($get)=>in_array($get('status'),[BankCheck::STATUS_COLLECTED,BankCheck::STATUS_CASHED],true))->required(fn($get)=>in_array($get('status'),[BankCheck::STATUS_COLLECTED,BankCheck::STATUS_CASHED],true)),
 Select::make('bank_account_id')->label('الحساب البنكي')->relationship('bankAccount','account_name',modifyQueryUsing:fn(Builder $q)=>$q->with('bank')->where('is_active',true))->getOptionLabelFromRecordUsing(fn($r)=>$r->displayName())->searchable()->preload()->visible(fn($get)=>in_array($get('status'),[BankCheck::STATUS_DEPOSITED,BankCheck::STATUS_COLLECTED,BankCheck::STATUS_CASHED],true))->required(fn($get)=>in_array($get('status'),[BankCheck::STATUS_COLLECTED,BankCheck::STATUS_CASHED],true)),
 Select::make('customer_id')->label('العميل')->relationship('customer','name')->searchable()->preload()->visible(fn($get)=>$get('type')===BankCheck::TYPE_INCOMING), Select::make('supplier_id')->label('المورد')->relationship('supplier','name')->searchable()->preload()->visible(fn($get)=>$get('type')===BankCheck::TYPE_OUTGOING),
 TextInput::make('drawer_bank')->label('البنك المسحوب عليه')->visible(fn($get)=>$get('type')===BankCheck::TYPE_INCOMING), TextInput::make('drawer_name')->label('اسم الساحب')->visible(fn($get)=>$get('type')===BankCheck::TYPE_INCOMING),
 TextInput::make('beneficiary_name')->label('اسم المستفيد')->visible(fn($get)=>$get('type')===BankCheck::TYPE_OUTGOING), TextInput::make('reference_number')->label('الرقم المرجعي'),
 ]),Textarea::make('notes')->label('البيان / الملاحظات')->rows(3)->columnSpanFull()]);} }